version: '3.8'

services:
  # Development service
  hpc-dashboard-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - hpc-network
    profiles:
      - dev

  # Production service
  hpc-dashboard-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - dashboard-data:/usr/share/nginx/html/data
      - dashboard-logs:/var/log/nginx
    networks:
      - hpc-network
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - hpc-dashboard-prod
    networks:
      - hpc-network
    profiles:
      - prod

networks:
  hpc-network:
    driver: bridge

volumes:
  dashboard-data:
    driver: local
  dashboard-logs:
    driver: local


